"""
Reactor noise model: stochastic neutron flux fluctuations.
==========================================================
Steady-state flux φ₀(x,y) is superimposed with a spatially and
temporally correlated noise field:

    φ(x,y,t) = φ₀(x,y) · [1 + δφ̃(x,y,t)]

δφ̃ is generated by an AR(1) process:

    δφ̃(t+Δt) = α · δφ̃(t) + √(1−α²) · η(x,y,t)

α = exp(−Δt/τ_c); η spatially filtered via FFT-based 2-D Gaussian convolution.
Pure NumPy — no SciPy dependency.

Why bother: real detectors never read a perfectly steady flux — there's always
"reactor noise" from boiling, vibration, turbulence. This generates physically
plausible noise (correlated in space *and* time, scaled by the local flux) so the
neutron-noise/PSD analysis on the frontend has something realistic to chew on.
"""
from __future__ import annotations
import numpy as np


def _fft_conv2d(arr: np.ndarray, kernel: np.ndarray) -> np.ndarray:
    """'same'-mode 2-D convolution done via FFT (multiply in frequency space).

    Rolling my own instead of scipy.signal.convolve2d to keep the zero-dependency
    rule. Zero-pad to the full linear-convolution size so wrap-around doesn't bleed
    across edges, then crop back to the original window.
    """
    H, W   = arr.shape
    kH, kW = kernel.shape
    pH, pW = H + kH - 1, W + kW - 1
    F = np.fft.rfft2(arr,    s=(pH, pW))
    G = np.fft.rfft2(kernel, s=(pH, pW))
    out = np.fft.irfft2(F * G, s=(pH, pW))
    sH, sW = kH // 2, kW // 2
    return out[sH: sH + H, sW: sW + W]


def _gaussian_kernel(sigma: float, truncate: float = 3.0) -> np.ndarray:
    """Separable 2-D Gaussian, normalised to sum 1. `sigma` sets the spatial
    correlation length of the noise; `truncate` decides how many sigmas of tail
    to keep before the kernel is negligibly small."""
    r   = max(1, int(truncate * sigma + 0.5))
    ax  = np.arange(-r, r + 1, dtype=float)
    k1d = np.exp(-0.5 * (ax / sigma) ** 2)
    k1d /= k1d.sum()
    return np.outer(k1d, k1d)   # outer product of two 1-D Gaussians = 2-D Gaussian


def generate(core_result: dict, n_steps=300, dt=0.005, amplitude=0.015,
             correlation_length=1.8, tau_c=0.10, seed=42) -> dict:
    """
    Simulate stochastic reactor noise on top of the steady-state flux.
    core_result must contain 'flux_thermal' and 'active_mask'.
    """
    rng  = np.random.default_rng(seed)
    phi0 = np.array(core_result["flux_thermal"], dtype=float)
    mask = np.array(core_result["active_mask"],  dtype=bool)
    H, W = phi0.shape

    # Normalise the steady flux to [0,1] so the noise amplitude is relative — the
    # fluctuation is largest where the flux is largest, which is physically right.
    phi_max  = phi0[mask].max() if mask.any() else 1.0
    phi_norm = np.where(mask, phi0 / (phi_max + 1e-12), 0.0)

    K     = _gaussian_kernel(max(0.3, correlation_length))
    # AR(1) coefficients: alpha sets the "memory" (how fast noise decorrelates in
    # time), sigma is chosen so the process has unit variance at steady state.
    alpha = float(np.exp(-dt / max(tau_c, 1e-6)))
    sigma = float(np.sqrt(max(0.0, 1.0 - alpha ** 2)))

    # Track the time series at the flux hot-spot — the most interesting detector spot.
    hs = tuple(int(x) for x in np.unravel_index(phi_norm.argmax(), phi_norm.shape))

    field      = np.zeros((H, W))
    timeseries = np.zeros(n_steps)
    rms_acc    = np.zeros((H, W))
    snap_every = max(1, n_steps // 20)   # keep ~20 animation frames, not all n_steps
    snapshots  = []

    for step in range(n_steps):
        # fresh white noise -> smooth it spatially -> renormalise to unit variance
        eta   = rng.standard_normal((H, W))
        eta_c = _fft_conv2d(eta, K)
        eta_c /= max(float(eta_c.std()), 1e-12)

        # AR(1) update gives temporal correlation; multiply by phi_norm for spatial shape
        field = alpha * field + sigma * eta_c
        delta = amplitude * field * phi_norm

        timeseries[step] = float(delta[hs[0], hs[1]])
        rms_acc          += delta ** 2     # accumulate for the RMS map afterwards
        if step % snap_every == 0:
            snapshots.append(np.round(delta * mask, 7).tolist())

    # Power spectral density of the hot-spot signal — bin 0 (DC) zeroed so the plot
    # isn't dominated by the mean. This is the neutron-noise spectrum you'd measure.
    freqs     = np.fft.rfftfreq(n_steps, d=dt)
    psd       = (np.abs(np.fft.rfft(timeseries)) ** 2) / n_steps
    psd[0]    = 0.0

    valid_psd = psd[1:]
    peak_idx  = int(np.argmax(valid_psd)) + 1 if len(valid_psd) > 0 else 1
    peak_freq = float(freqs[peak_idx]) if peak_idx < len(freqs) else 0.0

    rms_map  = np.sqrt(rms_acc / n_steps)   # spatial map of fluctuation strength
    rms_ts   = float(np.std(timeseries))    # overall noise level at the hot-spot

    return {
        "snapshots":          snapshots,
        "timeseries":         np.round(timeseries, 9).tolist(),
        "t":                  np.round(np.arange(n_steps) * dt, 6).tolist(),
        "rms_map":            np.round(rms_map * mask, 7).tolist(),
        "hotspot_ij":         list(hs),
        "freqs_hz":           np.round(freqs, 5).tolist(),
        "psd":                np.round(psd, 14).tolist(),
        "rms_noise_pct":      round(rms_ts * 100.0, 4),
        "peak_freq_hz":       round(peak_freq, 4),
        "amplitude":          amplitude,
        "correlation_length": correlation_length,
        "tau_c_s":            tau_c,
        "dt_s":               dt,
        "n_steps":            n_steps,
        "grid_shape":         [H, W],
    }
